### ISSUE TITLE
Filter always results in collision

### ISSUE THREAD

**Issue by dwarvenbuffet** [bakpakin/Splash.lua#2]
I noticed that in move_support it always uses a collision resolver even if the filter returns that no collision happened. This happens because on line 579 it does the following:
`local r = f and f(thing, thing2) or "slide"`
Even if the filter says no move_support still goes ahead and uses slide instead. It would be a good idea to fix this or have your docs reflect this.

**Comment by bakpakin** [comment]
No, this is an error. I will change this.
